NUMROUNDS = 'number rounds'

ANNOUNCE = 'announce'
ANNOUNCEIntro = 'intro'
ANNOUNCEMidround = 'mid round'
ANNOUNCEBetweenRound = 'between round'
ANNOUNCEGameOver = 'game over'

TOPICS = 'topics'
TOPICHealthgood = 'health good'
TOPICHealthok = 'health ok'
TOPICHealthlow = 'health low'
TOPICStaminagood = 'stamina good'
TOPICStaminaok = 'stamina ok'
TOPICStaminalow = 'stamina low'
TOPICBighit = 'bighit'
TOPICMiss = 'miss'
TOPICBoring = 'boring'
TOPICShowboat = 'showboat'
TOPICHardtohit = 'hard to hit'
# bonus hits should have their own topic - Haymaker etc, bolo punch, rope-a-dope

PLAYERNAME = 'player name'
OPPONENTNAME = 'opp name'
PLAYERHP = 'player hp'
PLAYERSTAMINA = 'player stamina'
OPPONENTHP = 'opponent hp'
OPPONENTSTAMINA = 'opponent stamina'
TURNS = 'turns'
CURRENTROUND = 'round'
CURRENTTURN = 'turn'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERHISTORY = 'player history'
OPPONENTHISTORY = 'opponent history'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERBONUS = 'player bonus'
OPPONENTBONUS = 'opponent bonus'

MOVEjab = 'jab'
MOVEhook = 'hook'
MOVEcross = 'cross'
MOVEuppercut = 'uppercut'
MOVEfeint = 'feint'
MOVEtaunt = 'taunt'
MOVEwrapup = 'wrapup'
MOVEbob = 'bobandweave'
MOVEfootwork = 'footwork'
MOVEhandsup = 'handsup'
MOVEprotect = 'protectbody'

ADadvantage = 'adv'
ADdisadvantage = 'dis'
ADsuper = 'super'
ADexhausted = 'exhausted'
ADNobonus = 'no bonus'
