NUMROUNDS = 'number rounds'

ANNOUNCEPrompt = 'prompt'
ANNOUNCEIntro = 'intro'
ANNOUNCEMidround = 'mid round'
ANNOUNCEBetweenRound = 'between round'
ANNOUNCEGameOver = 'game over'

TOPIC = 'topic'
TOPICHealthok = 'health ok'
TOPICHealthlow = 'health low'
TOPICTired = 'tired'
TOPICExhausted = 'exhausted'
TOPICBighit = 'bighit'
TOPICMiss = 'miss'
TOPICBoring = 'boring'
TOPICShowboat = 'showboat'
TOPICHardtohit = 'hard to hit'

PLAYERHP = 'player hp'
PLAYERSTAMINA = 'player stamina'
OPPONENTHP = 'opponent hp'
OPPONENTSTAMINA = 'opponent stamina'
TURNS = 'turns'
CURRENTROUND = 'round'
CURRENTTURN = 'turn'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERHISTORY = 'player history'
OPPONENTHISTORY = 'opponent history'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERBONUS = 'player bonus'
OPPONENTBONUS = 'opponent bonus'

MOVEjab = 'jab'
MOVEhook = 'hook'
MOVEcross = 'cross'
MOVEuppercut = 'uppercut'
MOVEfeint = 'feint'
MOVEtaunt = 'taunt'
MOVEwrapup = 'wrapup'
MOVEbob = 'bobandweave'
MOVEfootwork = 'footwork'
MOVEhandsup = 'handsup'
MOVEprotect = 'protectbody'

ADadvantage = 'adv'
ADdisadvantage = 'dis'
ADsuper = 'super'
ADexhausted = 'exhausted'
ADNobonus = 'no bonus'
