NUMROUNDS = 'number rounds'

ANNOUNCE = 'announce'
ANNOUNCEIntro = 'intro'
ANNOUNCEMidround = 'mid round'
ANNOUNCEBetweenRound = 'between round'
ANNOUNCEGameOver = 'game over'

TOPICS = 'topics'
TOPICHealthgood = 'health good'
TOPICHealthok = 'health ok'
TOPICHealthlow = 'health low'
TOPICStaminagood = 'stamina good'
TOPICStaminaok = 'stamina ok'
TOPICStaminalow = 'stamina low'
TOPICBighit = 'bighit'
TOPICMiss = 'miss'
TOPICBoring = 'boring'
TOPICShowboat = 'showboat'
TOPICHardtohit = 'hard to hit'
TOPICHit = 'hit'
TOPICBlocked = 'blocked'
TOPICWrapup = 'wrap up'
TOPICBothblock = 'both block'
TOPICFire = 'on fire'

# bonus hits should have their own topic - Haymaker etc, bolo punch, rope-a-dope

PLAYERNAME = 'player name'
OPPONENTNAME = 'opp name'
PLAYERHP = 'player hp'
PLAYERSTAMINA = 'player stamina'
OPPONENTHP = 'opponent hp'
OPPONENTSTAMINA = 'opponent stamina'
TURNS = 'turns'
CURRENTROUND = 'round'
CURRENTTURN = 'turn'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERHISTORY = 'player history'
OPPONENTHISTORY = 'opponent history'
PLAYERMOVE = 'player move'
OPPONENTMOVE = 'opponent move'
PLAYERBONUS = 'player bonus'
OPPONENTBONUS = 'opponent bonus'

MOVEjab = 'jab'
MOVEhook = 'hook'
MOVEcross = 'cross'
MOVEuppercut = 'uppercut'
MOVEfeint = 'feint'
MOVEtaunt = 'taunt'
MOVEwrapup = 'wrap up'
MOVEbob = 'bob and weave'
MOVEfootwork = 'footwork'
MOVEhandsup = 'gloves up'
MOVEprotect = 'protects the body'

ADadvantage = 'adv'
ADdisadvantage = 'dis'
ADsuper = 'super'
ADOnfire = 'fire'
ADexhausted = 'exhausted'
ADNobonus = 'no bonus'

INTENTName = 'name'
INTENTSlots = 'slots'
INTENTPunch = 'punchIntent'
INTENTUppercut = 'uppercutIntent'
INTENTJab = 'jabIntent'
INTENTBlock = 'blockpunchIntent'
INTENTSelect = 'sceneSelectIntent'
INTENTFootwork = 'footworkIntent'
INTENTCross = 'crossIntent'
INTENTHook = 'hookIntent'
INTENTBob = 'bobIntent'
INTENTTaunt = 'tauntIntent'
INTENTProtect = 'protectbodyIntent'
INTENTHandsup = 'handsupIntent'
INTENTFeint = 'feintIntent'

SLOTSBobandweave = 'duck'


SESSION = 'sessionAttributes'

AIType = 'ai type'
AIRandom = 'random moves'